/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.visao;

/**
 *
 * @author Alexandre
 */
public class TelaOS extends javax.swing.JFrame {

    /**
     * Creates new form TelaOS
     */
    public TelaOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblOsNumeroOS = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOsPecas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOsServicos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblOsNome = new javax.swing.JLabel();
        lblOsCPF = new javax.swing.JLabel();
        lblOsTelefone = new javax.swing.JLabel();
        lblOsEmail = new javax.swing.JLabel();
        lblOsRazaoSocial = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblOsStatus = new javax.swing.JLabel();
        lblOsCNPJ = new javax.swing.JLabel();
        lblOsContato = new javax.swing.JLabel();
        lblOsIE = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblOsMarca = new javax.swing.JLabel();
        lblOsModelo = new javax.swing.JLabel();
        lblOsPlaca = new javax.swing.JLabel();
        lblOsChassi = new javax.swing.JLabel();
        lblOsAno = new javax.swing.JLabel();
        lblOsKilometragem = new javax.swing.JLabel();
        lblOsNPatrimonio = new javax.swing.JLabel();
        lblOsAcessorio = new javax.swing.JLabel();
        btnOsAdicionarPeca = new javax.swing.JButton();
        btnOsRemoverPeca = new javax.swing.JButton();
        btnOsAdicionarServico = new javax.swing.JButton();
        btnOsRemoverServico = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        btnOsVoltar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ORDEM DE SERVIÇO");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("NÚMERO");

        lblOsNumeroOS.setText("printarNumeroOS");

        tableOsPecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Quantidade", "Preço Unitário", "Preço Total"
            }
        ));
        jScrollPane1.setViewportView(tableOsPecas);

        tableOsServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Serviço", "Responsável", "Preço"
            }
        ));
        jScrollPane2.setViewportView(tableOsServicos);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PEÇAS A SUBSTITUIR");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SERVIÇOS A EXECUTAR");

        lblOsNome.setText("NOME");

        lblOsCPF.setText("CPF");

        lblOsTelefone.setText("TELEFONE");

        lblOsEmail.setText("EMAIL");

        lblOsRazaoSocial.setText("RAZAOSOCIAL");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("STATUS");

        lblOsStatus.setText("printarStatus");

        lblOsCNPJ.setText("CNPJ");

        lblOsContato.setText("CONTATO");

        lblOsIE.setText("IE");

        jLabel16.setText("endereco...");

        lblOsMarca.setText("MARCA");

        lblOsModelo.setText("MODELO");

        lblOsPlaca.setText("PLACA");

        lblOsChassi.setText("CHASSI");

        lblOsAno.setText("ANO");

        lblOsKilometragem.setText("KILOMETRAGEM");

        lblOsNPatrimonio.setText("nPATRIMONIO");

        lblOsAcessorio.setText("Acessorio");

        btnOsAdicionarPeca.setText("Adicionar");

        btnOsRemoverPeca.setText("Remover");

        btnOsAdicionarServico.setText("Adicionar");

        btnOsRemoverServico.setText("Remover");

        jLabel25.setText("PRECO TOTAL DA OS?");

        btnOsVoltar.setText("Voltar");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("falta label!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblOsModelo)
                        .addGap(421, 421, 421))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel2))
                                .addComponent(lblOsNumeroOS)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblOsNome)
                                                .addGap(61, 61, 61)
                                                .addComponent(lblOsCPF)
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblOsContato)
                                                    .addComponent(lblOsTelefone)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblOsMarca)
                                                    .addGap(40, 40, 40)
                                                    .addComponent(lblOsPlaca))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblOsRazaoSocial)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(lblOsCNPJ))))
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblOsEmail)
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel16)
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel11)
                                                .addGap(9, 9, 9))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblOsIE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblOsStatus))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(88, 88, 88)
                                                .addComponent(lblOsChassi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(lblOsKilometragem)
                                                .addGap(53, 53, 53)))
                                        .addComponent(lblOsAcessorio)
                                        .addGap(113, 113, 113))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblOsAno)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(lblOsNPatrimonio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnOsAdicionarPeca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnOsRemoverPeca)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOsAdicionarServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOsRemoverServico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOsVoltar)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblOsNome)
                    .addComponent(lblOsCPF)
                    .addComponent(lblOsTelefone)
                    .addComponent(lblOsEmail)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOsNumeroOS)
                    .addComponent(lblOsRazaoSocial)
                    .addComponent(lblOsCNPJ)
                    .addComponent(lblOsContato)
                    .addComponent(lblOsIE)
                    .addComponent(lblOsStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOsMarca)
                    .addComponent(lblOsPlaca)
                    .addComponent(lblOsAno)
                    .addComponent(lblOsNPatrimonio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOsModelo)
                    .addComponent(lblOsChassi)
                    .addComponent(lblOsKilometragem)
                    .addComponent(lblOsAcessorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnOsAdicionarPeca)
                    .addComponent(btnOsRemoverPeca)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnOsAdicionarServico)
                    .addComponent(btnOsRemoverServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addGap(11, 11, 11)
                .addComponent(btnOsVoltar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOsAdicionarPeca;
    private javax.swing.JButton btnOsAdicionarServico;
    private javax.swing.JButton btnOsRemoverPeca;
    private javax.swing.JButton btnOsRemoverServico;
    private javax.swing.JButton btnOsVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblOsAcessorio;
    private javax.swing.JLabel lblOsAno;
    private javax.swing.JLabel lblOsCNPJ;
    private javax.swing.JLabel lblOsCPF;
    private javax.swing.JLabel lblOsChassi;
    private javax.swing.JLabel lblOsContato;
    private javax.swing.JLabel lblOsEmail;
    private javax.swing.JLabel lblOsIE;
    private javax.swing.JLabel lblOsKilometragem;
    private javax.swing.JLabel lblOsMarca;
    private javax.swing.JLabel lblOsModelo;
    private javax.swing.JLabel lblOsNPatrimonio;
    private javax.swing.JLabel lblOsNome;
    private javax.swing.JLabel lblOsNumeroOS;
    private javax.swing.JLabel lblOsPlaca;
    private javax.swing.JLabel lblOsRazaoSocial;
    private javax.swing.JLabel lblOsStatus;
    private javax.swing.JLabel lblOsTelefone;
    private javax.swing.JTable tableOsPecas;
    private javax.swing.JTable tableOsServicos;
    // End of variables declaration//GEN-END:variables
}
