/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.visao;

/**
 *
 * @author Aluno
 */
public class TelaInicial extends javax.swing.JFrame {

    private TelaAcessorio telaAcessorio;
    private TelaCliente telaCliente;
    private TelaFuncionario telaFuncionario;
    private TelaMarca telaMarca;
    private TelaModelo telaModelo;
    private TelaOS telaOS;
    private TelaPecas telaPecas;
    private TelaServicos telaServicos;
    private TelaVeiculo telaVeiculo;
    private TelaCriarOS telaCriarOS;

    public TelaInicial() {
        initComponents();
        telaAcessorio = new TelaAcessorio();
        telaCliente = new TelaCliente();
        telaFuncionario = new TelaFuncionario();
        telaMarca = new TelaMarca();
        telaModelo = new TelaModelo();
        telaOS = new TelaOS();
        telaPecas = new TelaPecas();
        telaServicos = new TelaServicos();
        telaVeiculo = new TelaVeiculo();
        telaCriarOS = new TelaCriarOS();
        comboboxTelasCadastro.addItem("Tela Acessorio");
        comboboxTelasCadastro.addItem("Tela Cliente");
        comboboxTelasCadastro.addItem("Tela Funcionario");
        comboboxTelasCadastro.addItem("Tela Marca");
        comboboxTelasCadastro.addItem("Tela Modelo");
        comboboxTelasCadastro.addItem("Tela OS");
        comboboxTelasCadastro.addItem("Tela Pecas");
        comboboxTelasCadastro.addItem("Tela Servicos");
        comboboxTelasCadastro.addItem("Tela Veiculo");
        comboboxTelasCadastro.addItem("Tela Criar OS");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comboboxTelasCadastro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("DINOCO");

        jButton1.setText("Abrir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboboxTelasCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxTelasCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(comboboxTelasCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxTelasCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboboxTelasCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxTelasCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxTelasCadastroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String selecao = (String) comboboxTelasCadastro.getSelectedItem();
        telaAcessorio.setVisible(false);
        telaCliente.setVisible(false);
        telaFuncionario.setVisible(false);
        telaMarca.setVisible(false);
        telaModelo.setVisible(false);
        telaOS.setVisible(false);
        telaPecas.setVisible(false);
        telaServicos.setVisible(false);
        telaVeiculo.setVisible(false);
        switch (selecao) {
            case "Tela Acessorio" ->
                telaAcessorio.setVisible(true);
            case "Tela Cliente" ->
                telaCliente.setVisible(true);
            case "Tela Funcionario" ->
                telaFuncionario.setVisible(true);
            case "Tela Marca" ->
                telaMarca.setVisible(true);
            case "Tela Modelo" ->
                telaModelo.setVisible(true);
            case "Tela OS" ->
                telaOS.setVisible(true);
            case "Tela Pecas" ->
                telaPecas.setVisible(true);
            case "Tela Servicos" ->
                telaServicos.setVisible(true);
            case "Tela Veiculo" ->
                telaVeiculo.setVisible(true);
            case "Tela Criar OS" ->
                telaCriarOS.setVisible(true);
            default -> {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboboxTelasCadastro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
