/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.visao;

import com.modelos.Acessorio;
import com.modelos.Modelo;
import com.modelos.Veiculo;
import com.modelos.crud.IAcessorioCRUD;
import com.modelos.crud.IMarcaCRUD;
import com.modelos.crud.IModeloCRUD;
import com.modelos.crud.IVeiculoCRUD;
import com.persistencia.AcessorioDAO;
import com.persistencia.ModeloDAO;
import com.persistencia.VeiculoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexandre
 */
public class TelaVeiculo extends javax.swing.JFrame {

    private IMarcaCRUD marcaBD = null;
    private IModeloCRUD modeloBD = null;
    private IAcessorioCRUD acessorioBD = null;
    private IVeiculoCRUD veiculoBD = null;

    /**
     * Creates new form telaVeiculo
     */
    public TelaVeiculo() {
        initComponents();
        setLocationRelativeTo(null);
        try {
            // Veiculo
            veiculoBD = new VeiculoDAO();
            // MODELOS
            modeloBD = new ModeloDAO();
            ArrayList<Modelo> listaDeModelos = null;
            listaDeModelos = modeloBD.obterListaDeModelo();
            comboboxVeiculoModelo.removeAllItems();
            for (int pos = 0; pos < listaDeModelos.size(); pos++) {
                comboboxVeiculoModelo.addItem(listaDeModelos.get(pos).toString());
            }
            // ACESSORIOS
            acessorioBD = new AcessorioDAO();
            ArrayList<Acessorio> listaDeAcesorios = null;
            listaDeAcesorios = acessorioBD.obterListaDeAcessorio();
            comboboxVeiculoAcessorio.removeAllItems();
            for (int pos = 0; pos < listaDeAcesorios.size(); pos++) {
                comboboxVeiculoAcessorio.addItem(listaDeAcesorios.get(pos).toString());
            }
            mostrarVeiculosNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Construtor Tela: " + erro.getMessage());
        }
    }

    private void limparTela() {
        txtVeiculoID.setText("");
        txtVeiculoPlaca.setText("");
        txtVeiculoChassi.setText("");
        txtVeiculoAno.setText("");
        txtVeiculoKilometragem.setText("");
        txtVeiculoNPatrimonio.setText("");
    }

    private void mostrarVeiculosNaGrid() {
        try {
            ArrayList<Veiculo> listaDeVeiculos = null;
            listaDeVeiculos = veiculoBD.obterListaDeVeiculo();
            DefaultTableModel model = (DefaultTableModel) tableVeiculo.getModel();
            model.setNumRows(0);
            if (listaDeVeiculos.isEmpty()) {
                throw new Exception("Lista de Veiculos BD Vazia");
            }
            for (int pos = 0; pos < listaDeVeiculos.size(); pos++) {
                Veiculo objVeiculo = listaDeVeiculos.get(pos);
                String[] linha = new String[8];
                linha[0] = objVeiculo.getIdVeiculo() + "";
                linha[1] = objVeiculo.getPlaca();
                linha[2] = objVeiculo.getChassi() + "";
                linha[3] = objVeiculo.getIdModelo() + "";
                linha[4] = objVeiculo.getAno() + "";
                linha[5] = objVeiculo.getKilometragem() + "";
                linha[6] = objVeiculo.getnPatrimonio() + "";
                linha[7] = objVeiculo.getIdAcessorio() + "";
                model.addRow(linha);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, erro.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtVeiculoID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtVeiculoPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVeiculo = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtVeiculoKilometragem = new javax.swing.JTextField();
        txtVeiculoChassi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtVeiculoNPatrimonio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboboxVeiculoAcessorio = new javax.swing.JComboBox<>();
        btnVeiculoSalvar = new javax.swing.JButton();
        btnVeiculoAlterar = new javax.swing.JButton();
        btnVeiculoVoltar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtVeiculoAno = new javax.swing.JTextField();
        comboboxVeiculoModelo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE VEÍCULOS");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Placa");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Chassi");

        tableVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Placa", "Chassi", "Modelo", "Ano", "Kilometragem", "Nº Patrimonio", "Acessório"
            }
        ));
        jScrollPane1.setViewportView(tableVeiculo);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Kilometragem");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Modelo");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Nº Patrimonio");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Acessório");

        comboboxVeiculoAcessorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnVeiculoSalvar.setText("Salvar");
        btnVeiculoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeiculoSalvarActionPerformed(evt);
            }
        });

        btnVeiculoAlterar.setText("Alterar");
        btnVeiculoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeiculoAlterarActionPerformed(evt);
            }
        });

        btnVeiculoVoltar.setText("Voltar");
        btnVeiculoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVeiculoVoltarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Ano");

        comboboxVeiculoModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel11)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addComponent(jLabel4))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVeiculoPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtVeiculoID, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtVeiculoChassi, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtVeiculoAno)
                            .addComponent(comboboxVeiculoModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboboxVeiculoAcessorio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVeiculoNPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVeiculoKilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVeiculoSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnVeiculoAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVeiculoVoltar)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtVeiculoKilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVeiculoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtVeiculoPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel5))
                            .addComponent(txtVeiculoChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVeiculoSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVeiculoAlterar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboboxVeiculoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtVeiculoAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtVeiculoNPatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboboxVeiculoAcessorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVeiculoVoltar)
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addGap(200, 200, 200))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVeiculoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeiculoSalvarActionPerformed
        try {
            Veiculo veiculo = null;
            int identificador = 0;
            String placa = txtVeiculoPlaca.getText();
            String chassi = txtVeiculoChassi.getText();
            String aux = (String) comboboxVeiculoModelo.getSelectedItem();
            String vetModelo[] = aux.split("-");
            int idModelo = Integer.parseInt(vetModelo[0]);
            String data = txtVeiculoAno.getText();
            int kilometragem = Integer.parseInt(txtVeiculoKilometragem.getText());
            String nPatrimonio = txtVeiculoNPatrimonio.getText();
            aux = (String) comboboxVeiculoAcessorio.getSelectedItem();
            String vetAcessorio[] = aux.split("-");
            int idAcessorio = Integer.parseInt(vetAcessorio[0]);
            veiculo = new Veiculo(identificador, placa, chassi, kilometragem, nPatrimonio, data, idAcessorio, idModelo);
            veiculoBD.incluir(veiculo);
            limparTela();
            mostrarVeiculosNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Incluir Visao: " + erro.getMessage());
        }
    }//GEN-LAST:event_btnVeiculoSalvarActionPerformed

    private void btnVeiculoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeiculoVoltarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVeiculoVoltarActionPerformed

    private void btnVeiculoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVeiculoAlterarActionPerformed
        try {
            Veiculo veiculo = null;
            int identificador = Integer.parseInt(txtVeiculoID.getText());
            String placa = txtVeiculoPlaca.getText();
            String chassi = txtVeiculoChassi.getText();
            String aux = (String) comboboxVeiculoModelo.getSelectedItem();
            String vetModelo[] = aux.split("-");
            int idModelo = Integer.parseInt(vetModelo[0]);
            String data = txtVeiculoAno.getText();
            int kilometragem = Integer.parseInt(txtVeiculoKilometragem.getText());
            String nPatrimonio = txtVeiculoNPatrimonio.getText();
            aux = (String) comboboxVeiculoAcessorio.getSelectedItem();
            String vetAcessorio[] = aux.split("-");
            int idAcessorio = Integer.parseInt(vetAcessorio[0]);
            veiculo = new Veiculo(identificador, placa, chassi, kilometragem, nPatrimonio, data, idAcessorio, idModelo);
            veiculoBD.alterar(veiculo);
            limparTela();
            mostrarVeiculosNaGrid();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Incluir Visao: " + erro.getMessage());
        }
    }//GEN-LAST:event_btnVeiculoAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVeiculoAlterar;
    private javax.swing.JButton btnVeiculoSalvar;
    private javax.swing.JButton btnVeiculoVoltar;
    private javax.swing.JComboBox<String> comboboxVeiculoAcessorio;
    private javax.swing.JComboBox<String> comboboxVeiculoModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVeiculo;
    private javax.swing.JTextField txtVeiculoAno;
    private javax.swing.JTextField txtVeiculoChassi;
    private javax.swing.JTextField txtVeiculoID;
    private javax.swing.JTextField txtVeiculoKilometragem;
    private javax.swing.JTextField txtVeiculoNPatrimonio;
    private javax.swing.JTextField txtVeiculoPlaca;
    // End of variables declaration//GEN-END:variables
}
